### ISSUE TITLE
How to use just one of the reducers to persist?

### ISSUE THREAD

**Issue by opensourcegeek** [vicentedealencar/redux-pouchdb#1]
Just wondering if it's possible to persist one of the reducers that I later pass it to combineReducers function?

**Comment by vicentedealencar** [comment]
The state of the reducer will be persisted only if the higher order reducer persistentReducer is called. So, yes it will work :)

**Comment by vicentedealencar** [comment]
Hi, I am not sure if I answered your question completely, so I will give some details and close this issue, if you think something is missing let me know.

On the current implementation `persistentReducer(reducer)` results on a document where the `_id` is the reducer name. It is fine to use combineReducers later as we need a single reducer to create the store.

I should let this clearer on the readme.

Thanks for opening issue #1!
