### ISSUE TITLE
Can't use with pouchdb6

### ISSUE THREAD

**Issue by seanseany** [vicentedealencar/redux-pouchdb#12]
Update dependency to latest version of pouchdb

**Comment by vicentedealencar** [comment]
I know don't have enough tests, but I ran then against pouchdb@6.0.6 and they passed.

Can you send a PR with a failing test?

I took a look at [the 6.0.0 release blog post](https://pouchdb.com/2016/09/05/pouchdb-6.0.0.html) and I don't think there should be nothing wrong.

I just released 0.1.1, if it is still not working for you what errors are you seeing?

**Comment by daaain** [comment]
0.1.1 is all working great for me (thanks for the library!), but would you mind doing another update to 6.1.1? I'd like to use PouchDB offline and they landed better ServiceWorker support in 6.1.0.

**Comment by vicentedealencar** [comment]
This library has no direct dependency on PouchDB

**Comment by daaain** [comment]
There's a direct `devDependency` on PouchDB: https://github.com/vicentedealencar/redux-pouchdb/blob/master/package.json#L49

If it was changed to a `peerDependency` then it would be possible to independently change PouchDB version in individual projects, but right now the only way to do that is to fork the project.
