### ISSUE TITLE
Can't use with pouchdb-react-native.

### ISSUE THREAD

**Issue by pedroparra** [vicentedealencar/redux-pouchdb#13]
Hi,
when import persistentStore, throw the next error:

Code:
```js
import { persistentStore } from 'redux-pouchdb';
```
![426327587_100043_17744933179950334863](https://cloud.githubusercontent.com/assets/3930607/20147747/a896dabc-a6a9-11e6-9ab5-c3225eaa4728.jpg)

---------
Test in Android
redux-pouchdb: ^0.1.1
pouchdb-react-native: ^6.1.18

Regards

**Comment by vicentedealencar** [comment]
Hi,
I really don't know what can be the problem as the src is all js and there are only 2 deps: `array.from` and `deep-equal`, but those should be safe too.

I don't think this error message is really helpful, maybe you could get a better error pointing the `package.json` dependency to a this cloned repo. Something like: `"redux-pouchdb": "../redux-couchdb"` 
(I am not sure if this is the best path to solve this, but I can't thing of anything else)

I never seen `redux-pouchdb` running on `react-native`, and it is really cool to see someone doing it.

If necessary, I am open to a PR. 
I would really like to support react-native.
