### ISSUE TITLE
Anonymous reducer function will crash `persistentReducer`

### ISSUE THREAD

**Issue by tdd** [vicentedealencar/redux-pouchdb#14]
Hey @vicentedealencar,

First, thanks for `redux-pouchdb`, it's really been a breeze to use!

Until recently, when I passed it a reducer obtained through a mechanism that yielded an anonymous function (unassigned arrow function, FYI). Took me a good while to track this down.

See, on [this line](https://github.com/vicentedealencar/redux-pouchdb/blob/master/src/index.js#L65) of `index.js` you’re creating the "reducer name" that you'll later use as `_id` for your doc, esp. on initial save, unless an explicit name was passed as second argument to `persistentReducer`.

Obviously, when the passed reducer is anonymous *and* there's no second argument passed (I didn't even know you could pass one), it'll just burn in flames when trying a `db.put`. You'll get a 412 `missing_id` PouchDB error.

I think the best strategy here would be to throw as soon as you realize the to-be-id is empty, or even blank. Perhaps include advice in the exception's message about the possible fixes?

Best,

**Comment by vicentedealencar** [comment]
Hi, great to hear this library is being useful.

Throwing a nice error message may be better then the 412, but maybe other solution is to change that line to something like `name = name || reducer.name || Math.random().toString()` so that we never hit the `missing_id`. I guess I prefer the later one, would it work out for you?

Thanks for your interest here.

**Comment by vicentedealencar** [comment]
Doesn't passing a second parameter to persistentReducer fix that missing_id?

**Comment by tdd** [comment]
Hey Vicente,

Yes, the lib is useful. I was talking with Nolan Lawson the other day at dotJS about how I much preferred this one—for my use cases—over other Redux/PouchDB middlewares, as a matter of fact, and he liked that feedback 😉 

What I'm worried about with the random string is: how do we get back our persisted state later? Doesn't a variable id over time introduce issues? I'm unclear on the data flow over time here.

As for the second parameter, yes, it fixes the issue, but I feel your README should further stress, in the Caveats part, that an anonymous reducer function would *mandate* a custom name being passed (unless we go random, if that doesn't introduce later issues).

Best,

**Comment by skosch** [comment]
@tdd Thanks a million for tracking this down. Passing in a name as a second argument is easy enough to do, but first you have to know that that's what you need to do. A proper error message would be enough to solve the problem, I think. Thanks again (also to @vicentedealencar for this super useful little library)!

**Comment by vicentedealencar** [comment]
Thanks, @skosch!
If you want to send a PR I would be happy to merge and repubblish the package.
