### ISSUE TITLE
Black/whitelist store keys

### ISSUE THREAD

**Issue by jamalx31** [vicentedealencar/redux-pouchdb#17]
is there a way to decide what part of each reducer will be persisted?
e.g: 
`{ a: [], b[] }`
and only want 'a' to be synced with the DB

**Comment by vicentedealencar** [comment]
Maybe you could use reducer composition

```
const yourPersistedAReducer = persistCollectionReducer(yourAReducer)
const yourABReducer = (state, action) => {
  return {
    a: yourPersistedAReducer(state, action),
    b: yourBReducer(state, action)
  }
}
```

ps: this is a sideproject not battletested and open to feature sugestions as PR :)
