### ISSUE TITLE
Reload array data from the DB

### ISSUE THREAD

**Issue by z4m0** [vicentedealencar/redux-pouchdb#19]
I'm not able to get the state back from the DB when I reload the app. Is there some way to do this?

**Comment by alsco77** [comment]
Thanks for the explanation bro! Apologies, I deleted my comment before
seeing this as I found an alternate solution.

Appreciate the limitation examples though. For my application, the data
storage will be relatively simple and I think that the queries and usage
will be quite basic so it fits fine with low overhead.

Have a nice day!
