### ISSUE TITLE
State not updated when a "pull" change is received

### ISSUE THREAD

**Issue by coroleu** [vicentedealencar/redux-pouchdb#23]
Hello, not really an issue but a question....

My state is not updated when a pull change (new doc) is received from remote Pouchdb. My reducer is a persistentCollectionReducer and while debugging I see an action of type '@@redux-pouchdb/UPDATE_ARRAY_REDUCER' is dispatched to my reducer. Should I implement that switch case in order to update my state? I thought the lib was doing that for us. Am I wrong?

Thanks for the support

**Comment by vicentedealencar** [comment]
Hi,
Yes, the library is supposed to handle this, looks like there is a bug there... maybe this higher order reducer is not that stable...

if you are willing to look into it here is the shortcutting happens
https://github.com/vicentedealencar/redux-pouchdb/blob/master/src/persistentArrayReducer.js#L91

I would happily accept PRs if you are up to it

Sorry about this issue, and the delayed response.
