### ISSUE TITLE
Question: Switch remote database in runtime

### ISSUE THREAD

**Issue by akana** [vicentedealencar/redux-pouchdb#24]
Hello!!

I develop an app which might sync to different remote Couchdb database. The database can be changed by user select option. Could you please explain how to switch remote database at runtime?

Any help would be appreciated!!

**Comment by vicentedealencar** [comment]
Hey there,

Sorry, but by the time I developed this package I didn't predicted this use case.

I would happily accept a PR if you are up to it.

Any thoughts on what that new api would look like?

**Comment by noamraph** [comment]
I think that redux-pouchdb-plus supports this.
