### ISSUE TITLE
Debug logging

### ISSUE THREAD

**Issue by andymikulski** [vicentedealencar/redux-pouchdb#3]
Currently, a lot of the debug `console.log`s are cluttering up my workspace (ex: http://i.imgur.com/xuTUaVM.png).

Can the `master` branch be devoid of logs, or at least have some sort of debug flag? Thank you!

**Comment by vicentedealencar** [comment]
This is ugly, sorry about that.

I will add something like this and call it everywhere instead of console.log:
``` js
const log = (...objs) => {
  if(process.env.NODE_ENV === 'development') console.log(...objs)
}
```

This is not ideal but that was the best way I found to debug tests so far...

Any better idea?

**Comment by hnordt** [comment]
@vicentedealencar it's ok to use process.env.NODE_ENV :+1:

**Comment by medihack** [comment]
+1 for nicer logs. And thanks for the very nice library. There are some other redux pouchdb libraries, but I think yours nailed it.
