### ISSUE TITLE
Problem while setting up the development environment.

### ISSUE THREAD

**Issue by medihack** [vicentedealencar/redux-pouchdb#5]
I would like to contribute some small enhancements to your library. Unfortunately I have problems setting thinks up.

When I install the dependencies with `npm install` it crashes with

<pre>
npm ERR! Linux 3.13.0-74-generic
npm ERR! argv "/home/kai/.nvm/versions/node/v5.5.0/bin/node" "/home/zeus/.nvm/versions/node/v5.5.0/bin/npm" "install"
npm ERR! node v5.5.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! redux-pouchdb@0.0.7 prepublish: `rimraf lib && babel src --out-dir lib`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the redux-pouchdb@0.0.7 prepublish script 'rimraf lib && babel src --out-dir lib'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the redux-pouchdb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rimraf lib && babel src --out-dir lib
npm ERR! You can get their info via:
npm ERR!     npm owner ls redux-pouchdb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/kai/Projects/redux-pouchdb/npm-debug.log
</pre>

When I call `rimraf lib && babel src --out-dir lib` myself I get this error:

<pre>
SyntaxError: src/save.js: Unexpected token (22:8)
  20 |     return loadReducer(reducerName).then(doc => {
  21 |       const newDoc = {
> 22 |         ...doc
     |         ^
  23 |       };
  24 | 
  25 |       if (Array.isArray(reducerState)) {
zeus@olympus2:~/Projects/redux-pouchdb$ npm install
</pre>

I using current Node and Babel.

Any idea? I must admit that I also never used the spread operator (`...`) in that way.

**Comment by medihack** [comment]
Ah, sure .. it's not part of babel, but of JSX (https://facebook.github.io/react/docs/jsx-spread.html). But the problem remains. How do we set it up then?

**Comment by vicentedealencar** [comment]
I like this new syntax too much, do you mind if we use (stage 2)[https://babeljs.io/docs/plugins/preset-stage-2/] instead of dropping it?

**Comment by medihack** [comment]
Yes, stage 2 would be another option. Unfortunately I had to rewrite a large portion of your plugin from scratch as one of my urgent projects needed some extra features that were not easy to integrate in your code. I also pushed it on Github (https://github.com/medihack/redux-pouchdb-plus). I added a note and a link to your repo right on the top. I hope that's ok.

**Comment by vicentedealencar** [comment]
This is awesome! I appreciate the mention, that is far too kind.
